version: '3'

services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    environment:
      TZ: Asia/Shanghai
      SMB: SMB1
    ports:
      - 139:139
      - 445:445
    volumes:
      - ./data:/mount
    command: '-u "smb;123456" -s "smb;/mount/;yes;no;yes;all;all;all" -w "WORKGROUP" -g "force user=smb" -g "guest account=smb"'
