version: "3.3"

services:
  ss-server:
    container_name: ss-server
    image: nasus/go-ss2
    ports:
      - 8488:8488
    command: go-shadowsocks2 -s 'ss://AEAD_CHACHA20_POLY1305:your-password@:8488' -verbose