version: "3.3"

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.17
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: kibana:7.17.17
    ports:
      - 5601:5601
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80

networks:
  default:
    external:
      name: basic_host