version: "3.3"

services:
  demo-php:
    container_name: demo-php
    image: nasus/php:php56-zendguardloader-dev
    volumes:
      - ./lxtx:/var/www/html
      - ./config/license:/zend_loader/license
    ports:
      - 80:80
  demo-redis:
    container_name: demo-redis
    image: redis
    volumes:
      - ./cache/redis:/data
    ports:
      - 6379:6379
  demo-mysql:
    container_name: demo-mysql
    image: nasus/mysql-x86:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./cache/mysql:/var/lib/mysql
      - ./config/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306