version: "3.3"

services:
  mongo:
    container_name: mongo
    image: mongo:4
    environment:
      MONGO_INITDB_DATABASE: yapi
  basic-yapi:
    container_name: basic-yapi
    build:
      context: ./
      dockerfile: Dockerfile
    image: nasus/yapi
    ports: 
      - 9090:9090
      - 3000:3000
    depends_on: 
      - mongo
    # 第一次启动使用
    # command: "yapi server"
    # 之后使用下面的命令
    command: "node /my-yapi/vendors/server/app.js"