version: '3'

volumes:
  ikev2-vpnss-data:

services:
  vpnss:
    image: nasus/vpnss
    restart: always
    env_file:
      - ./vpn.env
    ports:
      - "1080:1080"
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpnss-server
    container_name: ipsec-vpnss-server
    volumes:
      - ikev2-vpnss-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro