version: "3.3"

services:
  maven:
    container_name: maven
    image: maven:3.5-jdk-8
    volumes:
      - ./cache:/app
    command: /bin/bash -c "echo 'hello world' > /listen.txt && tail -f /listen.txt"
